highlight librich ctermfg=207 ctermbg=none

syntax keyword librich
	\ __vte_pty_fork __vte_pty_get_argv __vte_pty_get_pty_flags __vte_pty_spawn
	\ _vte_conv _vte_conv_close _vte_conv_open _vte_debug_init
	\ _vte_iso2022_get_encoded_width _vte_iso2022_process _vte_iso2022_process_single
	\ _vte_iso2022_state_free _vte_iso2022_state_get_codeset _vte_iso2022_state_new
	\ _vte_iso2022_state_set_codeset _vte_iso2022_unichar_width _vte_matcher_free
	\ _vte_matcher_free_params_array _vte_matcher_match _vte_matcher_new
	\ _vte_regex_compile _vte_regex_exec _vte_regex_free _vte_ring_append
	\ _vte_ring_fini _vte_ring_index _vte_ring_index_writable _vte_ring_init
	\ _vte_ring_insert _vte_ring_remove _vte_ring_resize _vte_ring_shrink
	\ _vte_ring_write_contents _vte_row_data_append _vte_row_data_fill
	\ _vte_row_data_insert _vte_row_data_remove _vte_row_data_shrink
	\ _vte_termcap_find_boolean _vte_termcap_find_numeric _vte_termcap_find_string
	\ _vte_termcap_find_string_length _vte_termcap_free _vte_termcap_new
	\ _vte_unistr_append_to_string _vte_unistr_append_unichar _vte_unistr_get_base
	\ vte_pty_close vte_pty_get_fd vte_pty_get_size vte_pty_get_type vte_pty_new
	\ vte_pty_new_foreign vte_pty_set_size vte_pty_set_term vte_pty_set_utf8
	\ vte_reaper_add_child vte_reaper_get vte_reaper_get_type
